#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $VIDEO_DB_USER LOGIN PASSWORD '$VIDEO_DB_PASSWORD';
    CREATE DATABASE video_service OWNER $VIDEO_DB_USER;

    CREATE ROLE $USER_DB_USER LOGIN PASSWORD '$USER_DB_PASSWORD';
    CREATE DATABASE user_service OWNER $USER_DB_USER;

    CREATE ROLE $PROCESSING_DB_USER LOGIN PASSWORD '$PROCESSING_DB_PASSWORD';
    CREATE DATABASE processing_service OWNER $PROCESSING_DB_USER;
EOSQL
