server {
    listen 80;
    server_name _;

    location /api/video/ {
        proxy_pass http://127.0.0.1:8000;
    }

    location /api/auth/ {
        proxy_pass http://127.0.0.1:8001;
    }
}