# Generated by Django 6.1 on 2026-09-13 14:42

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=videos.models.Video.video_upload_path),
        ),
    ]
